name: CI/CD Status
run-name: Full CI/CD Pipeline

permissions:
  contents: read
  actions: read 

on:
  push:
    branches: ["main", "development"]
    paths-ignore:
      - "*.md" # ignore all markdown files at root
      - "*.js" # ignore all js files at root
      - "*.ts" # ignore all ts files at root
      - "assets/**" # ignore root assets
      - "docs/**" # ignore all docs
      - "scripts/**" # ignore all scripts
      - "ssr/**" # ignore ssr files
      - ".github/**/*.md" # ignore markdown files for .github
      - ".github/FUNDING.yml" # ignore funding yml
      - ".eslintrc" # ignore eslint changes
      - ".gitignore" # ignore git ignore changes
  pull_request:
    branches: ["main", "development"]
    paths-ignore:
      - "*.md" # ignore all markdown files at root
      - "*.js" # ignore all js files at root
      - "*.ts" # ignore all ts files at root
      - "assets/**" # ignore root assets
      - "docs/**" # ignore all docs
      - "scripts/**" # ignore all scripts
      - "ssr/**" # ignore ssr files
      - ".github/**/*.md" # ignore markdown files for .github
      - ".github/FUNDING.yml" # ignore funding yml
      - ".eslintrc" # ignore eslint changes
      - ".gitignore" # ignore git ignore changes
  workflow_dispatch:

jobs:
  trigger-full-ci:
    name: CI
    uses: ./.github/workflows/lint-and-test.yml
    secrets: inherit
    with:
      target_env: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/development' && 'development' || 'invalid' }}
      node-version: "22.4.1"
      skip_deploy: ${{ github.event_name == 'pull_request' }} # skip deployment if it's a pull request